# Generated by Django 4.1.1 on 2022-10-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_weather', '0002_alter_city_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
